import type { Metadata } from "next";
import "./globals.css";
import LangSelector from "./LangSelector";
import Image from "next/image";
import Link from "next/link";
import { getSession, logout } from "@/lib/auth";
import Script from "next/script";
import { GoogleTranslate } from "./GoogleTranslate";
import { cookies } from "next/headers";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const se = await getSession()

  const getPrefLangCookie = async () => {
    return (await cookies()).get("googtrans")?.value ?? "en";
  };

  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-W4HYC689ZZ"
        />
        <Script id="google-analytics" >
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-W4HYC689ZZ');
        `}
        </Script>
      </head>
      <body
        className={`antialiased`}
      >
        <nav className="flex items-center justify-between px-6 py-4 bg-gradient-to-r from-pink-200 to-yellow-100 shadow-md fade-in-up">
          <Link href={"/"}>
            <div className="flex items-center space-x-2 mr-2">
              <div className="w-10 h-10 bg-blue-300 rounded-full flex items-center justify-center">
                <Image alt="" width={75} height={75} src="/lablogo.png" />
              </div>
              <span className="text-lg font-semibold">Labview</span>
            </div>
          </Link>
          <div className="flex space-x-2 lg:space-x-4 items-center">
            {/* <a href="home.html" className="px-4 py-2 rounded-full bg-pink-100 hover:bg-pink-200">Home</a> */}
            {!se && <Link href="login" className="px-2 lg:px-4 py-1 lg:py-2 rounded-full bg-pink-100 hover:bg-pink-200">Login</Link>}
            {!!se && <Link href="myTests" className="px-2 lg:px-4 py-1 lg:py-2 rounded-full bg-pink-100 hover:bg-pink-200">My Tests</Link>}
            <Link href="about" className="px-2 lg:px-4 py-1 lg:py-2 hidden md:block rounded-full bg-pink-100 hover:bg-pink-200">About Us</Link>
            {!se && <Link href="registerLab" className="px-2 lg:px-4 py-1 lg:py-2 rounded-full bg-pink-100 hover:bg-pink-200">Register A Lab</Link>}
            {!!se && <form action={logout}> <button className="px-2 lg:px-4 py-1 lg:py-2 rounded-full bg-pink-100 hover:bg-pink-200">Logout</button></form>}
            <GoogleTranslate prefLangCookie={await getPrefLangCookie()} />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
